create_clock -period 50.000 -name sgbus_clk [get_ports sgbus_clkp]
create_clock -period 10.000 -name aurora_refclk [get_ports aurora_refclkp]


create_clock -period 50.000 -name gtwiz_reset_clk_freerun_in_p [get_ports gtwiz_reset_clk_freerun_in_p]
create_clock -period 10.000 -name quad220_refclk [get_ports quad220_clk_p]
create_clock -period 10.000 -name quad221_refclk [get_ports quad221_clk_p]
create_clock -period 10.000 -name quad222_refclk [get_ports quad222_clk_p]
create_clock -period 10.000 -name quad225_refclk [get_ports quad225_clk_p]
create_clock -period 10.000 -name quad226_refclk [get_ports quad226_clk_p]
create_clock -period 10.000 -name quad227_refclk [get_ports quad227_clk_p]
create_clock -period 10.000 -name quad230_refclk [get_ports quad230_clk_p]
create_clock -period 10.000 -name quad231_refclk [get_ports quad231_clk_p]
create_clock -period 10.000 -name quad235_refclk [get_ports quad235_clk_p]
create_clock -period 10.000 -name quad236_refclk [get_ports quad236_clk_p]
create_clock -period 10.000 -name quad237_refclk [get_ports quad237_clk_p]

set_clock_groups -asynchronous -group [get_clocks sgbus_clk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks aurora_refclk]

set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad220_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad221_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad222_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad225_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad226_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad227_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad230_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad231_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad235_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad236_refclk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks quad237_refclk]